### ISSUE TITLE
mapping of endaoment categories to existing giveth categories

### ISSUE THREAD

**Issue by divine-comedian** [Giveth/impact-graph#1664]
endaoment has over 400 categories they use for their organizations. We should group these categories by similarity and map these groupings to existing categories within Giveth. 

this will allow existing and new features that utilize our categories to work fluidly with endaoment projects,  such as the similar projects component feature at the bottom of the project details page.

@mohammadranjbarz will provide a CSV of existing main and sub categories within Giveth. @divine-comedian will create the mapping and return a CSV file for mohammad to integrate

**Comment by divine-comedian** [comment]
I've gone through the list and added 2-4 categories per `nteeCode` from Endaoment Projects

There's also some new categories I think we should add, sorted by main category --> sub-category:

- [x] NGO --> Endaoment 
- [x] Art & Culture --> Religious
- [x] NGO --> Disaster Relief
- [x] Health & Wellness --> Recreation
- [x] Finance --> Financial Services
- [x] NGO --> International Aid

Here is the CSV of the mapping:

[Endaoment -_ Giveth Categories - Sheet3.csv](https://github.com/user-attachments/files/16072901/Endaoment.-_.Giveth.Categories.-.Sheet3.csv)

**Comment by mohammadranjbarz** [comment]
https://giveth-dapps-v2-git-4280showendaomentprojectsdetail-givethio.vercel.app/projects/ngo

**Comment by divine-comedian** [comment]
@LatifatAbdullahi to test: 

1. check for new sub-categories have been applied correctly and are found in the correct main category
 
![image](https://github.com/user-attachments/assets/138d21e2-f36d-41d5-99b0-d32733df4787)

2. you are able to see all endaoment projects by selecting the Endaoment sub-category from the NGO main category. 
3. Endaoment projects have the Endaoment sub-category applied to them as well as other sub-categories as defined in the CSV attached above. (you don't need to check all the projects, just check a few and make sure they are more or less correct.)
![image](https://github.com/user-attachments/assets/da43fec0-4fc9-4ebb-909f-93cd516f6050)

**Comment by LatifatAbdullahi** [comment]
@mohammadranjbarz 

Endaoment(NGO) Projects have only a single category attached to them

![image](https://github.com/user-attachments/assets/1a0e1841-9d8b-4da5-8308-d5be7fb51a40)

**Comment by mohammadranjbarz** [comment]
> @mohammadranjbarz
> 
> Endaoment(NGO) Projects have only a single category attached to them
> 
> ![image](https://private-user-images.githubusercontent.com/112261242/349598073-1a0e1841-9d8b-4da5-8308-d5be7fb51a40.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjEyOTQyNzQsIm5iZiI6MTcyMTI5Mzk3NCwicGF0aCI6Ii8xMTIyNjEyNDIvMzQ5NTk4MDczLTFhMGUxODQxLTlkOGItNGRhNS04MzA4LWQ1YmU3ZmI1MWE0MC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzE4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcxOFQwOTEyNTRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iYWZlYTdmMDk0MDljN2M4ZjlkMDVlMTFlOWNjMGVjZWYzOTQxNzVmMzExOWI0ZWZiNDNhMzg2YWVhOTlhMzZkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.N6e1u7Gd8B6PM1QYITHrNxmb_O21JTD3lHrb4bkoUi8)

@LatifatAbdullahi  @divine-comedian 
I fixed it


https://staging.giveth.io/project/mlop-tapang
<img width="1706" alt="Screenshot 1403-04-29 at 11 43 55 in the morning" src="https://github.com/user-attachments/assets/6524063b-3d00-4e40-bec8-803b5881c335">

**Comment by LatifatAbdullahi** [comment]
@mohammadranjbarz 

Some of these projects do not have the right categories and sub-categories

**Lillian Bay Foundation**

The ntee code: T22
The ntee description is :  **Private Independent Foundations** with sub-categories: **Endaoment** (NGO) and **"Registered Non-Profit** (NGO)


For this Specific project: I think it should have only one Major category(**NGO**) and two sub-categories :**Endaoment** and **"Registered Non-Profit** 



![ii](https://github.com/user-attachments/assets/63df42bf-0532-4899-89da-5689e512a61f)







**Safernet Brasil**

ntee code: W00
ntee description: Public and Societal Benefits - "Endaomenents" (NGO)  and  "Public goods"(Community)

![str](https://github.com/user-attachments/assets/2328baf9-892a-495f-aca1-fe4d4c2b7ec9)

**Comment by divine-comedian** [comment]
@LatifatAbdullahi - I think @mohammadranjbarz has fixed the issues, the misplaced categories appear to have been removed - could you test a few other projects to see if the issue's been resolved?

**Comment by LatifatAbdullahi** [comment]
@mohammadranjbarz 

After checking the first 15 projects these projects  still do not have the correct sub-category




**MLOP TAPANG**

The Category (Community) - Sub-category (Housing) not Peace and Justice

![tpt](https://github.com/user-attachments/assets/c23f3bca-2bb8-415c-8e07-5902571b4b18)



**Reach Out NGO**

The  "Ennvironmental & Energy" Category and the Sub-category (Sustainable cities...) are missing

Also the right Sub-catgeory for "Community" is **Public Goods**" not "Peace and Justice"


![tttt](https://github.com/user-attachments/assets/d9ae61fb-75a3-4c0a-941e-570d3e8c5408)

**Comment by mohammadranjbarz** [comment]
@LatifatAbdullahi  Can you check them again, both of them seems ok
* https://staging.giveth.io/project/reach-out-ngo
<img width="941" alt="Screenshot 1403-05-11 at 11 00 53 in the morning" src="https://github.com/user-attachments/assets/5a87f806-0f4a-4dce-aa45-32841f7640b1">

* https://staging.giveth.io/project/mlop-tapang
<img width="1345" alt="Screenshot 1403-05-11 at 11 01 27 in the morning" src="https://github.com/user-attachments/assets/d94c7939-aca6-4291-99a2-7c61b88079aa">

**Comment by LatifatAbdullahi** [comment]
@divine-comedian @mohammadranjbarz 

Test Update- Pass

NGO --> Endaoment - Pass
 Art & Culture --> Religious - Pass
 NGO --> Disaster Relief - Pass
 Health & Wellness --> Recreation - Pass
 Finance --> Financial Services - Pass
 NGO --> International Aid - Pass
 
 Also tested 13 random Projects and they are mapped to the right categories and sub-categories
