### ISSUE TITLE
Staging Errors - Constant Restarts

### ISSUE THREAD

**Issue by mhmdksh** [Giveth/impact-graph#1918]
There is an issue with the staging environment for impact-graph. Check the below errors:

<img width="1214" alt="Image" src="https://github.com/user-attachments/assets/fad75f9c-e03e-49fd-8c9b-fdd2144393c5" />

This is causing staging to restart all the time, it needs error handling.

More info on the Grafana Dashboard that can be found on this link:

https://logs.giveth.io/d/bf924fe2-302f-4920-bb57-e23fe708cb4f/impact-graph-error-logs-staging?orgId=1&from=now-6h&to=now&timezone=browser

CC: @divine-comedian @Giveth/devops

**Comment by CarlosQ96** [comment]
@mhmdksh I pushed a hotfix for this, havent seen the error since

**Comment by CarlosQ96** [comment]
Gunicorn is consuming a lot of resources I updated the server. And reduced workers and a strategy to free memory

**Comment by divine-comedian** [comment]
@CarlosQ96 is this resolved for now?

**Comment by mhmdksh** [comment]
@CarlosQ96 I think I can still see the error, last was yesterday:

<img width="2227" alt="Image" src="https://github.com/user-attachments/assets/81d12e89-0e3b-40a3-bafa-edae382f357d" />

However the restarts have stopped, I think you fixed the restarts but this error keeps on popping.

I was wondering if these are two separate issues

**Comment by divine-comedian** [comment]
@mhmdksh followed up the bug you reported in a new issue - let's call this done and we can focus on fixing the error in another iteration.

https://github.com/Giveth/impact-graph/issues/1925
