### ISSUE TITLE
Backend: Rainbowroll Donation distribution scripts

### ISSUE THREAD

**Issue by CarlosQ96** [Giveth/impact-graph#342]
After discussing with Mohammad this issue will be done with two scripts:
1. Update our Giv Script to also catch mainnet donations and create in our db the donation records.
2. Add a SegmentNotified column to donations to keep track which have been notified.
3. Add a script that notifies those donations that haven't been notified to customers.

**Comment by MoeNick** [comment]
@mohammadranjbarz would u pls put your comments here? as we talked earlier on this.

**Comment by mohammadranjbarz** [comment]
@MoeNick 
As I talked with @divine-comedian 
We have a use case, sometimes happens that we move some funds(ETH/XDAI/or other tokens) to multiple addresses(recipient address of projects)  by **Disperse** app, and we want to create donations for those transfers, 
My suggestion is add a page in admin bro, you enter the txHash of disperse transaction, something like this: https://blockscout.com/xdai/mainnet/tx/0xd10f17ce5671f6d1084a902f0d7df3edc5c877dd83705ef55b7dacbab72922db
and get price of donated token at time of donation from admin, then I get the transaction data from network, and create donation per every transfer of that transaction and besides, I can give this option to admin to enter a txHash of a normal transfer to create one donation for that transaction,
please correct me if I'm mistaken or my suggestion needs some changes

**Comment by divine-comedian** [comment]
we'll use CSV airdrop since it is built right into the gnosis-safe apps

![image](https://user-images.githubusercontent.com/67759413/152146007-67a60f7c-f6fd-4de3-88cd-4832171486b4.png)

**Comment by mohammadranjbarz** [comment]
@CarlosQ96  I moved it to in-progress because my side is not finishedd yet

**Comment by mohammadranjbarz** [comment]
<img width="1006" alt="Screen Shot 1400-11-24 at 12 19 40" src="https://user-images.githubusercontent.com/9850545/153745969-ed39783b-f8c2-4f1f-89e3-d939362bbe29.png">
@MoeNick  @divine-comedian 

I have implemented a new page in donation page, so after you donated to projects by csv airdrop, you need to have `txHash`, price USD of that token at that time, then I will get token transfers of that tx and add them to DB, 

Now I support **erc20** token transfers, because we didn't have any transaction of csv airdrop for **native** transfers ( And I and @aminlatifi  guessed it would have a little complexity),
and for making sure that erc20 token transfer works fine I need some token transfer of our token whitelists for final test (I tried to donate some **GIV** but it wasn't successful

I tested with this data:
```
token_type,token_address,receiver,value,id
erc20,0x4f4F9b8D5B4d0Dc10506e5551B0513B61fD59e75,0x3194Cd0B46183e8058AB3981Fa2F37e01BE7DF66,2000000000000000
erc20,0x4f4F9b8D5B4d0Dc10506e5551B0513B61fD59e75,0x2Ea846Dc38C6b6451909F1E7ff2bF613a96DC1F3,3000000000000000
```

And for mainnet I need some transactions to test 

**PS**: @CarlosQ96  has implemented something for sending notification for donations outside of saveDonation() mutation, so if you `uncheck` **segmentNotified** field, we would send segment event and the the email would sent to project owner

**Comment by MoeNick** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/All-Devs-61644589b92edf0016f6999c/issues/Giveth/impact-graph/342?planning-poker) with ZenHub @CarlosQ96

**Comment by MoeNick** [comment]
@divine-comedian @mohammadranjbarz need  csv sample , and transaction sample with whitelist givbacks tokens

**Comment by mohammadranjbarz** [comment]
> @divine-comedian @mohammadranjbarz need csv sample , and transaction sample with whitelist givbacks tokens

not CSV,  **csv airdrop** transaction sample 

@MoeNick  JFYI **csv airdrop** is an application like disperse that you can send tokens to multiple accounts with one transaction

**Comment by divine-comedian** [comment]
here you go! this is distributing DRGIV3 which will allow us to send out sample donations without using real funds on Gnosis Chain - All the addresses are currently projects on `next.giveth.io`. we won't necessarily need to have a whitelisted GIVbacks token to test this out for rainbow rolls - which is denominated in ETH.

[sample csv airdrop.csv](https://github.com/Giveth/impact-graph/files/8119433/sample.csv.airdrop.csv)

**Comment by divine-comedian** [comment]
alternatively you could try this one, which will distribute native tokens - on Gnosis Chain this will be xDAI - on mainnet this is ETH which is the network and the token we're using to distribute rainbow roll funds

[sample csv airdrop - native tokens.csv](https://github.com/Giveth/impact-graph/files/8119818/sample.csv.airdrop.-.native.tokens.csv)

**Comment by mohammadranjbarz** [comment]
> here you go! this is distributing DRGIV3 which will allow us to send out sample donations without using real funds on Gnosis Chain - All the addresses are currently projects on `next.giveth.io`. we won't necessarily need to have a whitelisted GIVbacks token to test this out for rainbow rolls - which is denominated in ETH.
> 
> [sample csv airdrop.csv](https://github.com/Giveth/impact-graph/files/8119433/sample.csv.airdrop.csv)
Thanks but trying it with your CSV and I get an error

<img width="1920" alt="Screen Shot 1400-12-04 at 20 12 03 1(2)" src="https://user-images.githubusercontent.com/9850545/155366239-53c4f9a9-87d0-4c7e-a98e-e4ac69e5e102.png">

**Comment by mohammadranjbarz** [comment]
> alternatively you could try this one, which will distribute native tokens - on Gnosis Chain this will be xDAI - on mainnet this is ETH which is the network and the token we're using to distribute rainbow roll funds
> 
> [sample csv airdrop - native tokens.csv](https://github.com/Giveth/impact-graph/files/8119818/sample.csv.airdrop.-.native.tokens.csv)

It has some complexity for handling native tokens, so Griff said as long as we use this, not end user we can use `WETH` instead of `ETH` tso we don't have to implement that now

**Comment by mohammadranjbarz** [comment]
> alternatively you could try this one, which will distribute native tokens - on Gnosis Chain this will be xDAI - on mainnet this is ETH which is the network and the token we're using to distribute rainbow roll funds
> 
> [sample csv airdrop - native tokens.csv](https://github.com/Giveth/impact-graph/files/8119818/sample.csv.airdrop.-.native.tokens.csv)

I think Griff said while we are using this it's ok to just use `erc20` tokens , `WETH` instead of `ETH` because implementing 
native token have complexity, 
@GriffGreen  Am I right?

**PS** Remeber this is the automatic way, if we want to add donations one by one manually in db, we can do everything that we want , it's time-consuming but almost possible everything we want

**Comment by mohammadranjbarz** [comment]
@WhyldWanderer  Now if we miss any donation, or we wanted to create a donation from a txHash we can use admin bro for that purpose

<img width="1133" alt="Screen Shot 1400-12-04 at 21 43 48" src="https://user-images.githubusercontent.com/9850545/155381601-98f8f9df-e023-40d0-951c-6341b1dc97ed.png">

You can test it by donating directly to a address of  a project and add it by this page  ( if the destination of txHAsh is not a project's recipient you would get error)

**Comment by divine-comedian** [comment]
@mohammadranjbarz  I found the error with the CSV file 

this one should work now 

[sample csv airdrop.csv](https://github.com/Giveth/impact-graph/files/8135417/sample.csv.airdrop.csv)

no problem in sending WETH

**Comment by mohammadranjbarz** [comment]
@divine-comedian 

I have problem on executing transaction with your `CSV` and I have lots of `DRGIV3` in my wallet
<img width="1920" alt="Screen Shot 1400-12-08 at 20 18 52 (2)" src="https://user-images.githubusercontent.com/9850545/155891755-ea46f0f8-bcbd-4ddb-992e-acbee3ad0320.png">



And I can't send `WETH` as well, it said I'm not the owner
<img width="511" alt="Screen Shot 1400-12-08 at 20 26 05" src="https://user-images.githubusercontent.com/9850545/155891824-a23fe256-b4ff-4d7d-a525-9c573f67c37b.png">



Can you just send very tiny amount of `WETH` to at least two addresses, and give me the `txHash` if you do that I can complete my tests on this issue

**Comment by divine-comedian** [comment]
@mohammadranjbarz  Strange, was the DRGIV3 or other assets in your wallet or in the gnosis-safe? they need to be in the gnosis-safe to be able to send them. 

Anyway here are the test transactions for DRGIV3 using CSV airdrop 
https://blockscout.com/xdai/mainnet/tx/0xc78dc8ed7e0e08cb41f6f7614afe380814f90148b82c0c0b5151769d74e79105

and the same thing but with WETH
https://blockscout.com/xdai/mainnet/tx/0x7a063fbb9dc674f814b8b7607e64f20e09ce4b891de72360d8be3e5ac92a4351

**Comment by mohammadranjbarz** [comment]
> @mohammadranjbarz Strange, was the DRGIV3 or other assets in your wallet or in the gnosis-safe? they need to be in the gnosis-safe to be able to send them.
> 
> Anyway here are the test transactions for DRGIV3 using CSV airdrop https://blockscout.com/xdai/mainnet/tx/0xc78dc8ed7e0e08cb41f6f7614afe380814f90148b82c0c0b5151769d74e79105
> 
> and the same thing but with WETH https://blockscout.com/xdai/mainnet/tx/0x7a063fbb9dc674f814b8b7607e64f20e09ce4b891de72360d8be3e5ac92a4351

Thanks a lot

<img width="1126" alt="Screen Shot 1400-12-09 at 09 54 34" src="https://user-images.githubusercontent.com/9850545/155979181-0ca6c9c3-3e55-4adc-bb2e-a56f071f966f.png">


You can fill the create donation form like this and you will see the donations are created, you can then filter donations with `txHash` to see whether donations are correct or not

**PS** If you uncheck `segmentNotified` it will send email for project owners with cronjob within 1 hour ( I'm not sure about the exact time), but if you want to not to send email for project owners you can check this field when creation

**Comment by MoeNick** [comment]
Hey @divine-comedian this is waiting for you to confirm and move to done :)

**Comment by divine-comedian** [comment]
Okay so I created a new transaction and sent out some WETH

https://blockscout.com/poa/xdai/tx/0xf248c5e272cc364718d72c2b3893404032ceeb76911eb66de2dcd0a5d5a5dad7

I then used the csv airdrop donation tool in the admin dashboard and created the donations in the DB 
https://serve.giveth.io/admin/resources/Donation/actions/Donation?filters.transactionId=0xf248c5e272cc364718d72c2b3893404032ceeb76911eb66de2dcd0a5d5a5dad7&page=1

I found my donations in the project page - However all of the donations are showing up as a donation date of **Jan 19, 1970**
Also another detail I noticed is that the sender address is saved as the person who initiated the transaction from the multisig - ideally we save this as the multisig itself. We can find this data on the transaction as *Interacted with*
![image](https://user-images.githubusercontent.com/67759413/156062764-bd3c3034-f88c-47e0-af0c-c52c03c24703.png)

I tried to create another airdrop donation but with DRGIV3 and I received an error saying `Invalid Token Symbol` 
![image](https://user-images.githubusercontent.com/67759413/156063422-d9610144-13d1-4f7b-ad3a-4cc8df927cc9.png)
Is this because DRGIV3 isn't whitelisted? 

Isn't it possible to fetch the token from the transaction itself? Also would there be a way to fetch price data using the tx hash / block number of the transaction, how are we fetching prices currently for giveth.io?

**Comment by mohammadranjbarz** [comment]
> 

1. Yeah tokens should be in our whitelist, so you can't create donation of non-whitelisted tokens
2. We  don't have price history for all tokens, so we have to get it in create donation form
3. Time of donations has been fixed
4. Do you say that sender address for https://blockscout.com/poa/xdai/tx/0xf248c5e272cc364718d72c2b3893404032ceeb76911eb66de2dcd0a5d5a5dad7 should be **0xB6D8D84CA33C2e8fE3be1f1B4B0B7dE57cCf4a3c**?
5. I removed `currency` from input form

**PS** I have deleted created donations by this `tx` from db, so you can test it again to see `createdAt` value

**Comment by divine-comedian** [comment]
> Do you say that sender address for https://blockscout.com/poa/xdai/tx/0xf248c5e272cc364718d72c2b3893404032ceeb76911eb66de2dcd0a5d5a5dad7 should be 0xB6D8D84CA33C2e8fE3be1f1B4B0B7dE57cCf4a3c?

Yes because this is the multisig that was holding the funds and sent them out

**Comment by divine-comedian** [comment]
tested it out 

https://next.giveth.io/project/2018-cmb
https://next.giveth.io/project/how-many-photos-is-too-many-photos
https://next.giveth.io/project/hugenduben

![image](https://user-images.githubusercontent.com/67759413/156381349-87bd54f2-8cfc-490e-9bcd-27cacd229932.png)

the date looks good! transactions showed up on the UI - however the donation sender is still showing as the "From" Address instead of the actual multisig - I would fix only this then I think this is done.

**Comment by mohammadranjbarz** [comment]
> tested it out
> 
> https://next.giveth.io/project/2018-cmb https://next.giveth.io/project/how-many-photos-is-too-many-photos https://next.giveth.io/project/hugenduben
> 
> ![image](https://user-images.githubusercontent.com/67759413/156381349-87bd54f2-8cfc-490e-9bcd-27cacd229932.png)
> 
> the date looks good! transactions showed up on the UI - however the donation sender is still showing as the "From" Address instead of the actual multisig - I would fix only this then I think this is done.

@divine-comedian 
Thanks for guiding me, now the fromAddress has been fixed, I deleted the donations that you had created, so you can create donations by https://blockscout.com/xdai/mainnet/tx/0xf248c5e272cc364718d72c2b3893404032ceeb76911eb66de2dcd0a5d5a5dad7 again

**Comment by divine-comedian** [comment]
donations now showing up as anonymous - I'm assuming this is our multisig 

![image](https://user-images.githubusercontent.com/67759413/156935862-245f30ce-8cd6-418d-8a0c-ec2b241889b6.png)

I think this is good enough to call done! 

@mohammadranjbarz  is this ready to use on the production db? Let me know so I can finalize the Rainbow Rolls distribution.

**Comment by mohammadranjbarz** [comment]
> donations now showing up as anonymous - I'm assuming this is our multisig
> 
> ![image](https://user-images.githubusercontent.com/67759413/156935862-245f30ce-8cd6-418d-8a0c-ec2b241889b6.png)
> 
> I think this is good enough to call done!
> 
> @mohammadranjbarz is this ready to use on the production db? Let me know so I can finalize the Rainbow Rolls distribution.

1. Yeah I have set the `annonymous` flag to `true` should I change it to `false`? ( And we should make sure there is a user with our multisig walletAddress in our db)

2. I don't know what is our plan to deploy our changes to production, I think we would do it when releasing the new Dapp ( typescript version), @MoeNick  @mateodaza  Am I right?

**Comment by MoeNick** [comment]
> > donations now showing up as anonymous - I'm assuming this is our multisig
> > ![image](https://user-images.githubusercontent.com/67759413/156935862-245f30ce-8cd6-418d-8a0c-ec2b241889b6.png)
> > I think this is good enough to call done!
> > @mohammadranjbarz is this ready to use on the production db? Let me know so I can finalize the Rainbow Rolls distribution.
> 
> 1. Yeah I have set the `annonymous` flag to `true` should I change it to `false`? ( And we should make sure there is a user with our multisig walletAddress in our db)
> 2. I don't know what is our plan to deploy our changes to production, I think we would do it when releasing the new Dapp ( typescript version), @MoeNick  @mateodaza  Am I right?

If it doesn't have side effects on the current live app, I'm ok to do it now. Or you can wait until next week with the Nowruz release.

**Comment by divine-comedian** [comment]
I'd love to do it now so I can complete the Rainbow Rolls issue and send funds out to projects.

**Comment by divine-comedian** [comment]
waiting for this to be pushed to production to finish out the rainbow rolls distro @MoeNick @CarlosQ96

**Comment by mohammadranjbarz** [comment]
> waiting for this to be pushed to production to finish out the rainbow rolls distro @MoeNick @CarlosQ96

@divine-comedian 

Now we have rainbow rolls feature on production, sorry for taking too much time, it was huge release so we couldn't do it sooner
